---
apiVersion: thingswise.com/v1
kind: entity
spec:
  class: model_0
  key: key_0
  lookups:
  - lookup_domain: Lookup
    lookup_field: key_0
    name: default
  rollup: true
  scope: model_1
  start_of_day: 0
  superclass:
  - '{package_0}abstract_model_0'
  tags: []
  timezone: Europe/Moscow
---
apiVersion: thingswise.com/v1
kind: primaryDataDomain
spec:
  class: model_0
  fields:
  - category: []
    index: true
    name: key_0
    type: string
  kind: lookup
  name: Lookup
---
apiVersion: thingswise.com/v1
kind: primaryDataDomain
spec:
  class: model_0
  fields:
  - category: []
    default_value: 0
    label:
      i18n:
        en-US: test
    name: test
    type: number
  name: domain_0
---
apiVersion: thingswise.com/v1
kind: operationalDataDomain
spec:
  class: model_0
  fields:
  - aggregated: false
    category: []
    kind: direct
    label:
      i18n:
        en-US: test
    name: domain_1.test
    original_name: test
    resolution:
    - 5s
    - 15s
    - 1min
    - 5min
    - 15min
    - 1h
    - 12h
    - 1d
    timeseries: true
    type: number
  name: domain_1
