---
apiVersion: thingswise.com/v1
kind: entity
spec:
  class: model_1
  key: key_0
  lookups:
  - lookup_domain: Lookup
    lookup_field: key_0
    name: default
  rollup: true
  scope: model_0
  start_of_day: 0
  superclass:
  - '{package_0}abstract_model_1'
  tags: []
  timezone: Europe/Moscow
---
apiVersion: thingswise.com/v1
kind: primaryDataDomain
spec:
  class: model_1
  fields:
  - category: []
    index: true
    name: key_0
    type: string
  kind: lookup
  name: Lookup
---
apiVersion: thingswise.com/v1
kind: primaryDataDomain
spec:
  class: model_1
  fields:
  - category: []
    default_value: 0
    name: property
    type: number
  name: domain_1
---
apiVersion: thingswise.com/v1
kind: operationalDataDomain
spec:
  class: model_1
  fields:
  - aggregated: false
    category: []
    kind: direct
    name: domain_0.state
    original_name: state
    resolution:
    - 15s
    - 1min
    - 5min
    timeseries: true
    type: number
  name: domain_0
---
apiVersion: thingswise.com/v1
kind: eventDomain
spec:
  class: model_1
  fields:
  - content:
      info:
      - domain_0.state
    formula:
    - 0
    - $domain_0.state
    - <=
    - 20
    - <=
    name: domain_2.alert
    raw_data_resolution: 1s
    severity: 0
    type: number
  name: domain_2
