---
apiVersion: thingswise.com/v1
kind: entity
spec:
  class: model_1
  key: key_1
  lookups:
  - lookup_domain: Lookup
    lookup_field: key_1
    name: default
  rollup: true
  scope: model_0
  start_of_day: 0
  superclass: []
  tags: []
  timezone: Europe/Moscow
---
apiVersion: thingswise.com/v1
kind: primaryDataDomain
spec:
  class: model_1
  fields:
  - category: []
    index: true
    name: key_0
    type: string
  - category: []
    index: true
    name: key_1
    type: string
  kind: lookup
  name: Lookup
---
apiVersion: thingswise.com/v1
kind: primaryDataDomain
spec:
  class: model_1
  fields:
  - category: []
    name: Name
    type: string
  name: Basic
---
apiVersion: thingswise.com/v1
kind: operationalDataDomain
spec:
  class: model_1
  fields:
  - aggregated: false
    category: []
    default_stats: avg
    group: temperature
    kind: direct
    name: domain_0.ceiling
    original_name: ceiling
    resolution:
    - 5s
    - 15s
    - 1min
    - 5min
    - 15min
    timeseries: true
    type: number
  - aggregated: false
    category: []
    default_stats: avg
    group: temperature
    kind: direct
    name: domain_0.floor
    original_name: floor
    resolution:
    - 5s
    - 15s
    - 1min
    - 5min
    - 15min
    timeseries: true
    type: number
  - aggregated: false
    category: []
    default_stats: avg
    group: string_group
    kind: direct
    name: domain_0.string
    original_name: string
    raw_data_resolution: 5s
    resolution: []
    timeseries: true
    type: string
  - aggregated: false
    category: []
    default_stats: avg
    group: string_group
    kind: direct
    name: domain_0.string1
    original_name: string1
    raw_data_resolution: 5s
    resolution: []
    timeseries: true
    type: string
  - aggregated: false
    category: []
    default_stats: avg
    kind: direct
    name: domain_0.output
    original_name: output
    resolution:
    - 5s
    - 15s
    - 1min
    - 5min
    - 15min
    timeseries: true
    type: number
  groups:
  - label:
      i18n: {}
    name: domain_0.temperature
  - label:
      i18n: {}
    name: domain_0.string_group
  name: domain_0
