---
apiVersion: thingswise.com/v1
kind: entity
spec:
  class: model_1
  key: key_1
  lookups:
  - lookup_domain: Lookup
    lookup_field: key_1
    name: default
  rollup: true
  scope: model_0
  start_of_day: 0
  superclass: []
  tags: []
  timezone: Europe/Moscow
---
apiVersion: thingswise.com/v1
kind: primaryDataDomain
spec:
  class: model_1
  fields:
  - category: []
    index: true
    name: key_0
    type: string
  - category: []
    index: true
    name: key_1
    type: string
  kind: lookup
  name: Lookup
---
apiVersion: thingswise.com/v1
kind: operationalDataDomain
spec:
  class: model_1
  fields:
  - aggregated: false
    category: []
    decimals: 1
    kind: direct
    name: domain_0.tensor
    original_name: tensor
    resolution: []
    timeseries: true
    type: string
  - aggregated: false
    category: []
    decimals: 1
    kind: direct
    name: domain_0.tensor_0
    original_name: tensor_0
    resolution: []
    timeseries: true
    type: string
  name: domain_0
