---
apiVersion: thingswise.com/v1
kind: entity
spec:
  class: model_1
  key: key_1
  lookups:
  - lookup_domain: Lookup
    lookup_field: key_1
    name: default
  rollup: true
  scope: model_0
  start_of_day: 0
  superclass: []
  tags: []
  timezone: Europe/Moscow
---
apiVersion: thingswise.com/v1
kind: primaryDataDomain
spec:
  class: model_1
  fields:
  - category: []
    index: true
    name: key_0
    type: string
  - category: []
    index: true
    name: key_1
    type: string
  kind: lookup
  name: Lookup
---
apiVersion: thingswise.com/v1
kind: operationalDataDomain
spec:
  class: model_1
  fields:
  - aggregated: false
    category: []
    kind: direct
    name: domain_0.real
    original_name: real
    resolution:
    - 5s
    - 15s
    - 1min
    - 5min
    - 15min
    - 1h
    - 12h
    - 1d
    timeseries: true
    type: number
  - aggregated: false
    category: []
    kind: direct
    name: domain_0.real_0
    original_name: real_0
    resolution:
    - 5s
    - 15s
    - 1min
    - 5min
    - 15min
    - 1h
    - 12h
    - 1d
    timeseries: true
    type: number
  - aggregated: false
    category: []
    kind: direct
    name: domain_0.real_1
    original_name: real_1
    resolution:
    - 5s
    - 15s
    - 1min
    - 5min
    - 15min
    - 1h
    - 12h
    - 1d
    timeseries: true
    type: number
  name: domain_0
