---
apiVersion: thingswise.com/v1
kind: entity
spec:
  class: model_1
  key: key_0
  lookups:
  - lookup_domain: Lookup
    lookup_field: key_0
    name: default
  rollup: true
  start_of_day: 0
  superclass:
  - '{package_0}abstract_model_1'
  tags: []
  timezone: Europe/Moscow
---
apiVersion: thingswise.com/v1
kind: primaryDataDomain
spec:
  class: model_1
  fields:
  - category: []
    index: true
    name: key_0
    type: string
  kind: lookup
  name: Lookup
